In [1]:
import numpy as np
import torch
import torch.nn as nn

### Data preparation
data = np.genfromtxt('data.csv', delimiter=',')
x_data = torch.from_numpy(data[:,0:1]).float()
y_data = torch.from_numpy(data[:,1:]).float()

print('X\n', x_data)
print('y\n', y_data)

X
 tensor([[6.7000],
        [4.6000],
        [3.5000],
        [5.5000]])
y
 tensor([[9.1000],
        [5.9000],
        [4.6000],
        [6.7000]])


In [2]:
# Create a linear layer
linear = nn.Linear(1, 1)

# set value (for illustration)
linear.weight.data = torch.Tensor([[-0.34]])
linear.bias.data = torch.Tensor([0.04])

# print
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[-0.3400]], requires_grad=True)
Parameter containing:
tensor([0.0400], requires_grad=True)


In [3]:
# some params
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(),
                            lr = 0.01)
epochs = 1

In [4]:
# training
for epoch in range(epochs):
    # y_hat
    y_hat = linear(x_data)
    print(f'y_hat: {y_hat}')

    # loss
    loss = loss_fn(y_hat, y_data)
    print(f'loss: {loss}')

    # Compute gradient
    loss.backward()
    print(f'(db, dw): ({linear.bias.grad.data}, {linear.weight.grad.data})')

    # update
    optimizer.step()
    optimizer.zero_grad()
    print(f'(b, w): ({linear.bias.data}, {linear.weight.data})')

y_hat: tensor([[-2.2380],
        [-1.5240],
        [-1.1500],
        [-1.8300]], grad_fn=<AddmmBackward0>)
loss: 72.37236022949219
(db, dw): (tensor([-16.5210]), tensor([[-88.5775]]))
(b, w): (tensor([0.2052]), tensor([[0.5458]]))


In [6]:
import numpy as np
import torch
import torch.nn as nn

### Data preparation
data = np.genfromtxt('data.csv', delimiter=',')
x_data = torch.from_numpy(data[:, 0:1]).float()
y_data = torch.from_numpy(data[:, 1:]).float()

# Create model, loss and optimizer
linear = nn.Linear(1, 1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), 
                            lr=0.01)

# training
epochs = 100
for epoch in range(epochs):
    y_hat = linear(x_data)
    loss = loss_fn(y_hat, y_data)
    print(f'loss: {loss}')
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()    

loss: 98.12348175048828
loss: 18.912599563598633
loss: 3.7002246379852295
loss: 0.7787008881568909
loss: 0.21762347221374512
loss: 0.10986742377281189
loss: 0.08917106688022614
loss: 0.08519447594881058
loss: 0.0844288170337677
loss: 0.08427999168634415
loss: 0.08424946665763855
loss: 0.08424173295497894
loss: 0.08423848450183868
loss: 0.08423581719398499
loss: 0.08423358201980591
loss: 0.08423139154911041
loss: 0.08422906696796417
loss: 0.08422666043043137
loss: 0.08422446250915527
loss: 0.084222212433815
loss: 0.08421988785266876
loss: 0.0842176303267479
loss: 0.08421546220779419
loss: 0.08421309292316437
loss: 0.08421097695827484
loss: 0.08420853316783905
loss: 0.08420645445585251
loss: 0.08420407772064209
loss: 0.08420196175575256
loss: 0.08419965207576752
loss: 0.08419753611087799
loss: 0.08419516682624817
loss: 0.08419308066368103
loss: 0.08419078588485718
loss: 0.08418849110603333
loss: 0.08418644219636917
loss: 0.0841842070221901
loss: 0.084182009100914
loss: 0.0841796994209289