In [1]:
import numpy as np
import torch
import torch.nn as nn

### Data preparation
data = np.genfromtxt('data.csv', delimiter=',')
x_data = torch.from_numpy(data[:,0:1])
y_data = torch.from_numpy(data[:,1])

print('X\n', x_data)
print('y\n', y_data)

X
 tensor([[6.7000],
        [4.6000],
        [3.5000],
        [5.5000]], dtype=torch.float64)
y
 tensor([9.1000, 5.9000, 4.6000, 6.7000], dtype=torch.float64)


In [2]:
# Create a linear layer
linear = nn.Linear(1, 1)

# set value (for illustration)
linear.weight.data = torch.Tensor([[-0.34]])
linear.bias.data = torch.Tensor([0.04])

# print
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[-0.3400]], requires_grad=True)
Parameter containing:
tensor([0.0400], requires_grad=True)


In [5]:
# some params
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), 
                            lr=0.01)
epochs = 1

In [6]:
# training
for epoch in range(epochs):
    for i in range(4):
        x = x_data[i].float()
        y = y_data[i:i+1].float()
        
        # y_hat
        y_hat = linear(x)
        print(f'y_hat: {y_hat.item()}')
        
        # loss        
        loss = loss_fn(y_hat, y)
        print(f'loss: {loss.item()}')
                    
        # compute gradient
        loss.backward()
        print(f'(db, dw): ({linear.bias.grad.data}, {linear.weight.grad.data})')
    
        # update
        optimizer.step()
        optimizer.zero_grad()
        print(f'(b, w): ({linear.bias.data}, {linear.weight.data} \n\n')

y_hat: 8.342219352722168
loss: 0.5742321014404297
(db, dw): (tensor([-1.5156]), tensor([[-10.1543]]))
(b, w): (tensor([0.2663]), tensor([[1.3092]]) 


y_hat: 6.288448810577393
loss: 0.15089240670204163
(db, dw): (tensor([0.7769]), tensor([[3.5737]]))
(b, w): (tensor([0.2585]), tensor([[1.2734]]) 


y_hat: 4.71550989151001
loss: 0.013342557474970818
(db, dw): (tensor([0.2310]), tensor([[0.8086]]))
(b, w): (tensor([0.2562]), tensor([[1.2653]]) 


y_hat: 7.215599060058594
loss: 0.26584258675575256
(db, dw): (tensor([1.0312]), tensor([[5.6716]]))
(b, w): (tensor([0.2459]), tensor([[1.2086]]) 


