# AI VIET NAM # Softmax Regression

In [1]:
import numpy as np
import matplotlib.pyplot as plt 

**Sample 1**

In [4]:
x = np.array([[1.0, 0.5]])
Y = np.array([0])

In [10]:
def convert_one_hot(y, k):
    one_hot = np.zeros((len(y), k))
    one_hot[np.arange(len(y)), y] = 1
    return one_hot

n_classes = 2
Y_one_hot = convert_one_hot(Y, n_classes)
Y_one_hot

array([[1., 0.]])

In [7]:
y = Y_one_hot[0]

In [8]:
x, y

(array([[1. , 0.5]]), array([1., 0.]))

In [11]:
theta = np.array([[0.1, 0.2], [0.3, 0.4]])
theta

array([[0.1, 0.2],
       [0.3, 0.4]])

In [12]:
# define softmax function 
def softmax_function(z):
    return np.exp(z) / np.sum(np.exp(z))

In [13]:
# compute y_hat
def predict(x, theta):
    z = np.dot(x, theta)
    y_hat = np.exp(z) / np.sum(np.exp(z))
    return z, y_hat

z, y_hat = predict(x, theta)
z, y_hat

(array([[0.25, 0.4 ]]), array([[0.46257015, 0.53742985]]))

In [15]:
# compute loss
def compute_loss(y_hat, y):
    loss = -np.log(np.sum(y_hat*y, axis=1))
    return loss

loss = compute_loss(y_hat, y)
loss

array([0.77095705])

In [16]:
# compute gradient
def comput_gradient(y_hat, y, x):
    gradient = np.dot(x.transpose(), (y_hat - y))
    return gradient

gradient = comput_gradient(y_hat, y, x)
gradient

array([[-0.53742985,  0.53742985],
       [-0.26871492,  0.26871492]])

In [18]:
# update weights
learning_rate = 0.1
theta -= (learning_rate * gradient)
theta

array([[0.15374298, 0.14625702],
       [0.32687149, 0.37312851]])

In [19]:
# compute y_hat
def predict(x, theta):
    z = np.dot(x, theta)
    y_hat = np.exp(z) / np.sum(np.exp(z))
    return z, y_hat

z, y_hat = predict(x, theta)
z, y_hat

(array([[0.31717873, 0.33282127]]), array([[0.49608945, 0.50391055]]))

In [20]:
# compute loss
def compute_loss(y_hat, y):
    loss = -np.log(np.sum(y_hat*y, axis=1))
    return loss

loss = compute_loss(y_hat, y)
loss

array([0.70099904])

**Sample 2**

In [21]:
x = np.array([[1.0, 1.0]])
Y = np.array([0])

In [22]:
def convert_one_hot(y, k):
    one_hot = np.zeros((len(y), k))
    one_hot[np.arange(len(y)), y] = 1
    return one_hot

n_classes = 2
Y_one_hot = convert_one_hot(Y, n_classes)
Y_one_hot

array([[1., 0.]])

In [23]:
y = Y_one_hot

In [24]:
x, y

(array([[1., 1.]]), array([[1., 0.]]))

In [25]:
theta = np.array([[0.1, 0.2], [0.3, 0.4]])
theta

array([[0.1, 0.2],
       [0.3, 0.4]])

In [26]:
# define softmax function
def softmax_function(z):
    return np.exp(z) / np.sum(np.exp(z))

In [27]:
# compute y_hat
def predict(x, theta):
    z = np.dot(x , theta)
    y_hat = softmax_function(z)
    return z, y_hat

z, y_hat = predict(x, theta)
z, y_hat

(array([[0.4, 0.6]]), array([[0.450166, 0.549834]]))

In [28]:
# compute loss
def compute_loss(y_hat, y):
    loss = -np.log(np.sum(y_hat*y, axis=1))
    return loss

loss = compute_loss(y_hat, y)
loss

array([0.79813887])

In [29]:
# compute gradient
def compute_gradient(y_hat, y, x):
    gradient = np.dot(x.transpose(), (y_hat - y))
    return gradient

gradient = compute_gradient(y_hat, y, x)
gradient

array([[-0.549834,  0.549834],
       [-0.549834,  0.549834]])

In [30]:
# update weights
learning_rate = 0.1
theta -= (learning_rate * gradient)
theta

array([[0.1549834, 0.1450166],
       [0.3549834, 0.3450166]])

In [31]:
# compute y_hat
def predict(x, theta):
    z = np.dot(x , theta)
    y_hat = np.exp(z) / np.sum(np.exp(z))
    return z, y_hat

z, y_hat = predict(x, theta)
z, y_hat

(array([[0.5099668, 0.4900332]]), array([[0.50498323, 0.49501677]]))

In [32]:
# compute loss
def compute_loss(y_hat, y):
    loss = -np.log(np.sum(y_hat*y, axis=1))
    return loss

loss = compute_loss(y_hat, y)
loss

array([0.68323005])

**Prediction**

In [33]:
x_test = np.array([1.0, 0.25])
z, y_hat = predict(x_test, theta)
pred = np.argmax(y_hat)
pred

0

In [34]:
z, y_hat

(array([0.24372925, 0.23127075]), array([0.50311458, 0.49688542]))

In [35]:
x_test = np.array([1.0, 4.5])
z, y_hat = predict(x_test, theta)
pred = np.argmax(y_hat)
pred

0